### Create Item 
POST http://localhost:3000/api/items HTTP/1.1
Content-Type: application/json

{
    "name": "item03",
    "description": "description of item03",
    "price": 1.0
}

### Get All items
GET http://localhost:3000/api/items HTTP/1.1
Content-Type: application/json


### Update an Item 
PUT http://localhost:3000/api/items/1 HTTP/1.1
Content-Type: application/json

{
    "name": "item01",
    "description": "item renamed to 01",
    "price": 1.2
}


### Delete an Item failed case
DELETE http://localhost:3000/api/items/s1s HTTP/1.1